package com.innowise.orderservice.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class which represents a separate item in an order. Associates a product with its quantity.
 * <p>
 * This class maps to the "order_items" table in the database.
 * Implements the order-item relationship with quantity attribute.
 * </p>
 */
@Entity
@Table(name = "order_items")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderItem {
    /**
     * Unique identifier for the order item. Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The order that contains the item.
     */
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;

    /**
     * The item associated with the order.
     */
    @ManyToOne
    @JoinColumn(name = "item_id")
    private Item item;

    /**
     * Quantity of items in the order.
     */
    @Column(name = "quantity")
    private Integer quantity;
}