package com.innowise.orderservice.model.entity;

import com.innowise.orderservice.model.entity.enums.OrderStatus;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.NamedSubgraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity class which represents an order.
 * <p>
 * This class maps to the "orders" table in the database.
 * Stores order header information including user reference, status,
 * creation date, and associated order items.
 * </p>
 */
@Entity
@Table(name = "orders")
@NamedEntityGraph(
        name = "Order.withItems",
        attributeNodes = {
                @NamedAttributeNode(value = "orderItems", subgraph = "orderItems")
        },
        subgraphs = {
                @NamedSubgraph(
                        name = "orderItems",
                        attributeNodes = {
                                @NamedAttributeNode("item")
                        }
                )
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order {
    /**
     * Unique identifier for the order. Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Reference to the user who placed this order.
     */
    @Column(name = "user_id")
    private Long userId;

    /**
     * Current state of the order.
     */
    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private OrderStatus status;

    /**
     * Date and time when the order was created.
     */
    @Column(name = "creation_date")
    @CreationTimestamp
    private LocalDateTime creationDate;

    /**
     * Collection of items included in this order.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> orderItems;

    @PrePersist
    public void setDefaultStatus() {
        if (status == null) {
            status = OrderStatus.PROCESSING;
        }
    }

    public void addOrderItem(OrderItem orderItem) {
        if (this.orderItems == null) {
            this.orderItems = new ArrayList<>();
        }

        this.orderItems.add(orderItem);
        orderItem.setOrder(this);
    }
}