package com.innowise.userservice.model.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.List;

/**
 * Entity class which represents a user.
 * <p>
 * This class maps to the "users" table in the database.
 * Contains personal information about the user and associated cards.
 * </p>
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {
    /** Unique identifier for the user. Automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User's first name. */
    @Column(name = "name")
    private String name;

    /** User's last name (surname). */
    @Column(name = "surname")
    private String surname;

    /** User's date of birth. */
    @Column(name = "birth_date")
    private LocalDate birthDate;

    /** User's email address. Must be unique across all users. */
    @Column(name = "email")
    private String email;

    /** List of cards associated with this user. Each user can have multiple cards. */
    @OneToMany(mappedBy = "user", cascade = CascadeType.REMOVE)
    private List<Card> cards;
}