package com.innowise.paymentservice.model.entity;

import com.innowise.paymentservice.model.entity.enums.PaymentStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.FieldType;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class with represents a payment.
 * <p>
 *  This class maps to the "payments" collection in MongoDB and stores information about payment
 *  attempts associated with orders. The payment status is determined based on a random number generation
 *  from an external API.
 * </p>
 */
@Getter
@Setter
@Builder
@Document(collection = "payments")
@NoArgsConstructor
@AllArgsConstructor
public class Payment {
    /**
     * Unique identifier for the payment document. Automatically generated by MongoDB as ObjectId.
     */
    @Id
    private String id;

    /**
     * Identifier of the associated order.
     */
    @Field(value = "order_id")
    private Long orderId;

    /**
     * Identifier of the user who placed the order.
     */
    @Field(value = "user_id")
    private Long userId;

    /**
     * Final outcome of the payment processing attempt.
     */
    @Field(value = "status", targetType = FieldType.STRING)
    @Builder.Default
    private PaymentStatus status = PaymentStatus.PROCESSING;

    /**
     * Timestamp when the payment record was created.
     */
    @Field(value = "timestamp")
    @Builder.Default
    private LocalDateTime timestamp = LocalDateTime.now();

    /**
     * Total amount to be paid for the order.
     */
    @Field(value = "payment_amount", targetType = FieldType.DECIMAL128)
    private BigDecimal paymentAmount;
}